"""add shopping_list_id in product

Revision ID: 67d4cb9e7af8
Revises: 2bf773ceb432
Create Date: 2025-01-23 03:57:01.068787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d4cb9e7af8'
down_revision: Union[str, None] = '2bf773ceb432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('shopping_list_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'shopping_lists', ['shopping_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'shopping_list_id')
    # ### end Alembic commands ###
