"""fixed model relationships

Revision ID: 96642451e1cf
Revises: f7057345614e
Create Date: 2025-01-23 03:12:55.970764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96642451e1cf'
down_revision: Union[str, None] = 'f7057345614e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('brands_user_id_fkey', 'brands', type_='foreignkey')
    op.drop_constraint('brands_list_id_fkey', 'brands', type_='foreignkey')
    op.drop_column('brands', 'list_id')
    op.drop_column('brands', 'user_id')
    op.drop_constraint('products_user_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('products_user_id_fkey', 'products', 'users', ['user_id'], ['id'])
    op.add_column('brands', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('brands', sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('brands_list_id_fkey', 'brands', 'lists', ['list_id'], ['id'])
    op.create_foreign_key('brands_user_id_fkey', 'brands', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
