"""removed bidirecional relationships

Revision ID: b52a31474e55
Revises: 0ba35a3f1fbf
Create Date: 2025-01-23 18:25:25.817419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52a31474e55'
down_revision: Union[str, None] = '0ba35a3f1fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('list_id', sa.Integer(), nullable=False))
    op.drop_constraint('products_shopping_list_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'shopping_lists', ['list_id'], ['id'])
    op.drop_column('products', 'shopping_list_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('shopping_list_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_shopping_list_id_fkey', 'products', 'shopping_lists', ['shopping_list_id'], ['id'])
    op.drop_column('products', 'list_id')
    # ### end Alembic commands ###
