"""testando relações bidirecionais novamente

Revision ID: bfdd97d519d4
Revises: 80cb213f853f
Create Date: 2025-01-24 23:04:18.782453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfdd97d519d4'
down_revision: Union[str, None] = '80cb213f853f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
