"""fix shopping_list_id in product

Revision ID: de40bd4e5b54
Revises: 67d4cb9e7af8
Create Date: 2025-01-23 04:05:04.874894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de40bd4e5b54'
down_revision: Union[str, None] = '67d4cb9e7af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
